In [ ]:
from math import copysign, hypot
import numpy as np
from numpy.linalg import inv

In [ ]:
def givens_rotation(A):
    (num_rows, num_cols) = np.shape(A)
    Q = np.identity(num_rows)
    R = np.copy(A)

    (rows, cols) = np.tril_indices(num_rows, -1, num_cols)
    print(rows, cols)
    for (row, col) in zip(rows, cols):

        if R[row, col] != 0:
            (c, s) = Givens_Rotation_Matrix_Entries(R[col, col], R[row, col])

            G = np.identity(num_rows)
            G[[col, row], [col, row]] = c
            G[row, col] = s
            G[col, row] = -s
            R = np.dot(G, R)
            Q = np.dot(Q, G.T)
    return (Q, R)

def Givens_Rotation_Matrix_Entries(a, b):
    r = hypot(a, b)
    c = a/r
    s = -b/r

    return (c, s)

In [ ]:

np.set_printoptions(precision=10, suppress=True)

A = np.array([[1, -2, 3, -4], [5, -6, 7, -8], [9, 0, -1, 2],[-3, 4, -5, 6],[-7, 8, 9, 0]], dtype='float')

Q, R = givens_rotation(A)



In [ ]:
Q

array([[ 0.0778498944, -0.1808726186,  0.2309909693, -0.860930308 ,
        -0.4082482905],
       [ 0.3892494721, -0.3853373178,  0.5659278748,  0.4615831169,
        -0.4082482905],
       [ 0.7006490497,  0.7077624204,  0.0571061007, -0.0700154166,
        -0.          ],
       [-0.2335496832,  0.2831049682, -0.3984594221,  0.1996735955,
        -0.8164965809],
       [-0.5449492609,  0.4875696674,  0.6814233595,  0.0311179629,
         0.          ]])

In [ ]:
R

array([[12.8452325787, -7.7849894416, -1.4791479939, -3.4253953543],
       [-0.          ,  7.7067463559, -0.9751393348,  6.9203436665],
       [-0.          ,  0.          , 12.7224692764, -7.7279312066],
       [-0.          , -0.          ,  0.          ,  0.8090670364],
       [ 0.          , -0.          , -0.          ,  0.          ]])

In [ ]:
q = Q.transpose()

In [ ]:
q

array([[ 0.0778498944,  0.3892494721,  0.7006490497, -0.2335496832,
        -0.5449492609],
       [-0.1808726186, -0.3853373178,  0.7077624204,  0.2831049682,
         0.4875696674],
       [ 0.2309909693,  0.5659278748,  0.0571061007, -0.3984594221,
         0.6814233595],
       [-0.860930308 ,  0.4615831169, -0.0700154166,  0.1996735955,
         0.0311179629],
       [-0.4082482905, -0.4082482905, -0.          , -0.8164965809,
         0.          ]])

In [ ]:
b=np.array([[-12],[-28],[-4],[20],[50]],dtype='float')

In [ ]:
Q@R

array([[ 1., -2.,  3., -4.],
       [ 5., -6.,  7., -8.],
       [ 9.,  0., -1.,  2.],
       [-3.,  4., -5.,  6.],
       [-7.,  8.,  9.,  0.]])

In [ ]:
q@b

array([[-46.5542368609],
       [ 40.1694493733],
       [  7.2556830027],
       [  3.2362681457],
       [  0.          ]])

In [ ]:
x1=-1.00000000004
x2=1.99999999988
x3=3.00000000007
x4=4.00000000012