In [ ]:
from math import copysign, hypot
import numpy as np
from numpy.linalg import inv

In [ ]:
def gram_schmidt(X):
    O = np.zeros(X.shape)
    for i in range(X.shape[1]):
        # orthogonalization
        vector = X[:, i]
        space = O[:, :i]
        projection = vector @ space
        vector = vector - np.sum(projection * space, axis=1)
        # normalization
        norm = np.sqrt(vector @ vector)
        vector /= abs(norm) < 1e-8 and 1 or norm
        
        O[:, i] = vector
    return O

In [ ]:
np.set_printoptions(precision=10, suppress=True)

# Input matrix
A = np.array([[1,-4], [2,3], [2,2]], dtype='float')

Q = gram_schmidt(A)


In [ ]:
R = Q.T @ A

In [ ]:
R

array([[3., 2.],
       [0., 5.]])

In [ ]:
Q

array([[ 0.3333333333, -0.9333333333],
       [ 0.6666666667,  0.3333333333],
       [ 0.6666666667,  0.1333333333]])

In [ ]:
Q.T

array([[ 0.3333333333,  0.6666666667,  0.6666666667],
       [-0.9333333333,  0.3333333333,  0.1333333333]])

In [ ]:
Q@R

array([[ 1., -4.],
       [ 2.,  3.],
       [ 2.,  2.]])

In [ ]:
b=np.array([[-3],[15],[9]],dtype='float')

In [ ]:
Q.T@b

array([[15.],
       [ 9.]])