In [ ]:
from math import copysign, hypot
import numpy as np
from numpy.linalg import inv

In [ ]:
def Hausholder(A):
  
    n, m = A.shape
    Q = np.eye(n)
    R = np.copy(A)

    for k in range(m):
        v = np.copy(R[k:, k]).reshape((n-k, 1))
        v[0] = v[0] + np.sign(v[0]) * np.linalg.norm(v)
        v = v / np.linalg.norm(v)
        R[k:, k:] = R[k:, k:] - 2 * v @ v.T @ R[k:, k:]
        Q[k:] = Q[k:] - 2 * v @ v.T @ Q[k:]

    return Q[:m], R[:m]

In [ ]:
np.set_printoptions(precision=10, suppress=True)

# Input matrix
A = np.array([[1,-4],[2,3],[2,2]], dtype='float')

Q, R = Hausholder(A)


In [ ]:
Q

array([[-0.3333333333, -0.6666666667, -0.6666666667],
       [ 0.9333333333, -0.3333333333, -0.1333333333]])

In [ ]:
R

array([[-3., -2.],
       [-0., -5.]])

In [ ]:
q = Q.transpose()

In [ ]:
q

array([[-0.3333333333,  0.9333333333],
       [-0.6666666667, -0.3333333333],
       [-0.6666666667, -0.1333333333]])

In [ ]:
q@R

array([[ 1., -4.],
       [ 2.,  3.],
       [ 2.,  2.]])

In [ ]:
b=np.array([[-3],[15],[9]],dtype='float')

In [ ]:
Q@b

array([[-15.],
       [ -9.]])