In [ ]:
import math
import numpy as np

def doolittle(A):
    
    n = A.shape[0]
    
    U = np.zeros((n, n), dtype=np.double)
    L = np.eye(n, dtype=np.double)
    
    for k in range(n):
        
        U[k, k:] = A[k, k:] - L[k,:k] @ U[:k,k:]
        L[(k+1):,k] = (A[(k+1):,k] - L[(k+1):,:] @ U[:,k]) / U[k, k]
    
    return L, U

In [ ]:
A = np.array([[8, -9, 1, -2],
	[-16, 21, -6, 9],
	[24, -39, 25, -32],
  [-40, 63, -71, 92]])
L, U = doolittle(A)

In [ ]:
L

array([[ 1.,  0.,  0.,  0.],
       [-2.,  1.,  0.,  0.],
       [ 3., -4.,  1.,  0.],
       [-5.,  6., -7.,  1.]])

In [ ]:
U

array([[ 8., -9.,  1., -2.],
       [ 0.,  3., -4.,  5.],
       [ 0.,  0.,  6., -6.],
       [ 0.,  0.,  0., 10.]])

In [ ]:
def crout(A):
    
    n = A.shape[0]
    
    U = np.zeros((n, n), dtype=np.double)
    L = np.zeros((n, n), dtype=np.double)
    
    for k in range(n):
        
        L[k, k] = A[k, k] - L[k, :] @ U[:, k]
        
        U[k, k:] = (A[k, k:] - L[k, :k] @ U[:k, k:]) / L[k, k]
        L[(k+1):, k] = (A[(k+1):, k] - L[(k+1):, :] @ U[:, k]) / U[k, k]
    
    return L, U

In [ ]:
A = np.array([[8, -9, 1, -2],
	[-16, 21, -6, 9],
	[24, -39, 25, -32],
  [-40, 63, -71, 92]])

L, U = crout(A)


In [ ]:
L

array([[  8.,   0.,   0.,   0.],
       [-16.,   3.,   0.,   0.],
       [ 24., -12.,   6.,   0.],
       [-40.,  18., -42.,  10.]])

In [ ]:
U

array([[ 1. , -1.1,  0.1, -0.2],
       [ 0. ,  1. , -1.3,  1.7],
       [ 0. ,  0. ,  1. , -1. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [ ]:
def cholesky(A):
    
    n = A.shape[0]
    
    L = np.zeros((n, n), dtype=np.double)
    
    for k in range(n):
        
        L[k, k] = np.sqrt(A[k, k] - np.sum(L[k, :] ** 2))
        
        L[(k+1):, k] = (A[(k+1):, k] - L[(k+1):, :] @ L[:, k]) / L[k, k]
    
    return L

In [ ]:
A = np.array([[8, -9, 1, -2],
	[-16, 21, -6, 9],
	[24, -39, 25, -32],
  [-40, 63, -71, 92]])
L = cholesky(A)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


In [ ]:
L

array([[  2.8,   0. ,   0. ,   0. ],
       [ -5.7,   nan,   0. ,   0. ],
       [  8.5,   nan,   nan,   0. ],
       [-14.1,   nan,   nan,   nan]])

Soru 6 ile ilgili

In [ ]:
def qr(A):

    m, n = A.shape
    Q = np.eye(m)
    for i in range(n - (m == n)):
        H = np.eye(m)
        
        H[i:, i:] = make_householder(A[i:, i])
        Q = Q@H
        A = H@A
    return Q, A
 
def make_householder(a):
  
    u = a / (a[0] + np.copysign(np.linalg.norm(a), a[0]))
    u[0] = 1
    H = np.eye(a.shape[0])
    
    H -= (2 / np.dot(u, u)) * u[:, None] @ u[None, :]
    return H

In [ ]:
A = np.array([[1, -2, 3, -4], [5, -6, 7, -8], [9, 0, -1, 2],[-3, 4, -5, 6],[-7, 8, 9, 0]], dtype='float')


In [ ]:
Q, R = qr(A)

In [ ]:
Q.round(5)

array([[ 0.1, -0.2,  0.2, -0.9, -0.4],
       [ 0.4, -0.4,  0.6,  0.5, -0.4],
       [ 0.7,  0.7,  0.1, -0.1, -0. ],
       [-0.2,  0.3, -0.4,  0.2, -0.8],
       [-0.5,  0.5,  0.7,  0. ,  0. ]])

In [ ]:
R.round(5)

array([[12.8, -7.8, -1.5, -3.4],
       [-0. ,  7.7, -1. ,  6.9],
       [-0. ,  0. , 12.7, -7.7],
       [-0. , -0. ,  0. ,  0.8],
       [ 0. , -0. , -0. ,  0. ]])

In [ ]:
def qr_factorization(A):
   
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))
    for j in range(n):
        v = A[:, j]
        for i in range(j - 1):
            q = Q[:, i]
            R[i, j] = q @ v
            v = v - R[i, j] * q
        norm = np.linalg.norm(v)
        Q[:, j] = v / norm
        R[j, j] = norm
    return Q, R

In [ ]:
A = np.array([[1, -2, 3, -4], [5, -6, 7, -8], [9, 0, -1, 2],[-3, 4, -5, 6],[-7, 8, 9, 0]], dtype='float')
Q, R = qr_factorization(A)

In [ ]:
Q

array([[ 0.1, -0.2,  0.2, -0.3],
       [ 0.4, -0.5,  0.6, -0.4],
       [ 0.7,  0. ,  0. ,  0.5],
       [-0.2,  0.4, -0.4,  0.4],
       [-0.5,  0.7,  0.6, -0.6]])

In [ ]:
R

array([[12.8,  0. , -1.5, -3.4],
       [ 0. , 11. ,  0. ,  4.9],
       [ 0. ,  0. , 12.8,  0. ],
       [ 0. ,  0. ,  0. ,  9.2]])

In [ ]:


from math import copysign, hypot

import numpy as np



def givens_rotation(A):

    (num_rows, num_cols) = np.shape(A)
    
    # Initialize Q,R
    # Q = orthogonal matrix
    # R =  upper triangular matrix
    Q = np.identity(num_rows)
    R = np.copy(A)

    # Iterate over lower triangular matrix.
    (rows, cols) = np.tril_indices(num_rows, -1, num_cols)
    print(rows, cols)
    for (row, col) in zip(rows, cols):

        # Compute Givens rotation matrix and
        # zero-out lower triangular matrix entries.
        if R[row, col] != 0:
            (c, s) = Givens_Rotation_Matrix_Entries(R[col, col], R[row, col])

            G = np.identity(num_rows)
            G[[col, row], [col, row]] = c
            G[row, col] = s
            G[col, row] = -s

            R = np.dot(G, R)
            Q = np.dot(Q, G.T)

    return (Q, R)


##### Compute matrix entries for Givens rotation. #####

def Givens_Rotation_Matrix_Entries(a, b):
    r = hypot(a, b)
    c = a/r
    s = -b/r

    return (c, s)

In [ ]:
#####   Example of  QR decomposition using Givens rotation.


np.set_printoptions(precision=1, suppress=True)

# Input matrix
A = np.array([[1, -2, 3, -4], [5, -6, 7, -8], [9, 0, -1, 2],[-3, 4, -5, 6],[-7, 8, 9, 0]], dtype='float')

(Q, R) = givens_rotation(A)



[1 2 2 3 3 3 4 4 4 4] [0 0 1 0 1 2 0 1 2 3]


In [ ]:
# Print orthogonal matrix Q
print('\n The Q matrix is equal to:\n\n',Q)

# Print upper triangular matrix R
print('\n The R matrix is equal to:\n\n',R)


 The Q matrix is equal to:

 [[ 0.1 -0.2  0.2 -0.9 -0.4]
 [ 0.4 -0.4  0.6  0.5 -0.4]
 [ 0.7  0.7  0.1 -0.1 -0. ]
 [-0.2  0.3 -0.4  0.2 -0.8]
 [-0.5  0.5  0.7  0.   0. ]]

 The R matrix is equal to:

 [[12.8 -7.8 -1.5 -3.4]
 [-0.   7.7 -1.   6.9]
 [-0.   0.  12.7 -7.7]
 [-0.  -0.   0.   0.8]
 [ 0.  -0.  -0.   0. ]]


In [ ]:
import numpy as np


In [ ]:
def lu(A):
    
    #Get the number of rows
    n = A.shape[0]
    
    U = A.copy()
    L = np.eye(n, dtype=np.double)
    
    #Loop over rows
    for i in range(n):
            
        #Eliminate entries below i with row operations 
        #on U and reverse the row operations to 
        #manipulate L
        factor = U[i+1:, i] / U[i, i]
        L[i+1:, i] = factor
        U[i+1:] -= factor[:, np.newaxis] * U[i]
        
    return L, U

In [ ]:
from numpy.lib.function_base import append
import numpy as np
A = np.random.randint(100, size=(50, 50))



In [ ]:
A

array([[ 4,  4, 43, ...,  4, 37, 24],
       [65, 30, 83, ..., 92, 19, 99],
       [62, 91, 93, ..., 99, 48, 24],
       ...,
       [44, 33,  4, ..., 16, 80, 46],
       [89, 31, 47, ..., 23, 22,  6],
       [21, 52, 67, ..., 74, 83, 75]])

In [ ]:
A = A.astype('float64')


L , U =lu(A)

In [ ]:
L

array([[ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [16.25      ,  1.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [15.5       , -0.82857143,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [11.        ,  0.31428571,  0.25420355, ...,  1.        ,
         0.        ,  0.        ],
       [22.25      ,  1.65714286, -0.10209139, ...,  1.74332019,
         1.        ,  0.        ],
       [ 5.25      , -0.88571429,  0.6497492 , ...,  0.12058921,
         0.38152427,  1.        ]])

In [ ]:
U

array([[ 4.00000000e+00,  4.00000000e+00,  4.30000000e+01, ...,
         4.00000000e+00,  3.70000000e+01,  2.40000000e+01],
       [ 0.00000000e+00, -3.50000000e+01, -6.15750000e+02, ...,
         2.70000000e+01, -5.82250000e+02, -2.91000000e+02],
       [ 0.00000000e+00, -3.55271368e-15, -1.08369286e+03, ...,
         5.93714286e+01, -1.00793571e+03, -5.89114286e+02],
       ...,
       [ 0.00000000e+00,  3.29954980e-15, -1.95252835e-13, ...,
        -6.66592775e+02,  3.46012694e+02,  1.70198547e+02],
       [ 0.00000000e+00,  7.34163333e-16,  1.15268361e-12, ...,
         0.00000000e+00,  4.92258948e+01,  2.34589744e+02],
       [ 0.00000000e+00, -5.16005025e-15,  2.72360761e-13, ...,
         0.00000000e+00,  0.00000000e+00,  1.29895227e+02]])

In [ ]:
from math import copysign, hypot

import numpy as np


def gram_schmidt_process(A):
    """Perform QR decomposition of matrix A using Gram-Schmidt process."""
    (num_rows, num_cols) = np.shape(A)

    # Initialize empty orthogonal matrix Q.
    Q = np.empty([num_rows, num_rows])
    cnt = 0

    # Compute orthogonal matrix Q.
    for a in A.T:
        u = np.copy(a)
        for i in range(0, cnt):
            proj = np.dot(np.dot(Q[:, i].T, a), Q[:, i])
            u -= proj

        e = u / np.linalg.norm(u)
        Q[:, cnt] = e

        cnt += 1  # Increase columns counter.

    # Compute upper triangular matrix R.
    R = np.dot(Q.T, A)

    return (Q, R)

In [ ]:
from numpy.lib.function_base import append
import numpy as np
A = np.random.randint(100, size=(50, 50))
A = A.astype('float64')

Q,R=gram_schmidt_process(A)

In [ ]:
Q

array([[ 0.06530458,  0.04630408,  0.16127467, ...,  0.04015583,
         0.09448469,  0.05657347],
       [ 0.08037487,  0.26262333, -0.00821998, ..., -0.01164225,
         0.22817551, -0.08503027],
       [ 0.24112461, -0.05884026, -0.06982952, ...,  0.19592348,
        -0.01709523,  0.08128511],
       ...,
       [ 0.03265229,  0.20062842,  0.20507642, ...,  0.13393773,
        -0.05254952,  0.00566847],
       [ 0.05776944,  0.29124851,  0.19826417, ..., -0.24422941,
         0.14597213,  0.15563056],
       [ 0.08037487,  0.19976711, -0.11936495, ...,  0.20770373,
         0.06268915,  0.01713327]])

In [ ]:
R

array([[ 3.98134399e+02,  2.98243508e+02,  2.92315862e+02, ...,
         3.13946748e+02,  3.13964330e+02,  3.41887062e+02],
       [-1.77635684e-15,  2.70458518e+02,  1.22989996e+02, ...,
         1.24057548e+02,  9.17300626e+01,  1.25322003e+02],
       [-4.52970994e-14, -3.54993812e-14,  2.18357271e+02, ...,
         4.88628041e+01,  7.61750054e+01,  2.92439828e+01],
       ...,
       [ 7.87814258e-13,  9.62896429e-13,  8.13238366e-13, ...,
         4.50199811e+01,  1.55108386e+01,  2.04514606e+01],
       [ 2.53130850e-14,  1.72334369e-13,  3.72202269e-14, ...,
        -1.76809956e-12,  4.29903347e+01, -1.65792251e+01],
       [-8.98625618e-12, -6.45039577e-12, -6.07380812e-12, ...,
        -1.10375042e-11, -2.50688359e-13,  1.16950356e+01]])

In [ ]:
def householder_reflection(A):
    """Perform QR decomposition of matrix A using Householder reflection."""
    (num_rows, num_cols) = np.shape(A)

    # Initialize orthogonal matrix Q and upper triangular matrix R.
    Q = np.identity(num_rows)
    R = np.copy(A)

    # Iterative over column sub-vector and
    # compute Householder matrix to zero-out lower triangular matrix entries.
    for cnt in range(num_rows - 1):
        x = R[cnt:, cnt]

        e = np.zeros_like(x)
        e[0] = copysign(np.linalg.norm(x), -A[cnt, cnt])
        u = x + e
        v = u / np.linalg.norm(u)

        Q_cnt = np.identity(num_rows)
        Q_cnt[cnt:, cnt:] -= 2.0 * np.outer(v, v)

        R = np.dot(Q_cnt, R)
        Q = np.dot(Q, Q_cnt.T)

    return (Q, R)

In [ ]:
from numpy.lib.function_base import append
import numpy as np
A = np.random.randint(100, size=(50, 50))
A = A.astype('float64')

Q,R= householder_reflection(A)

In [ ]:
Q

array([[ 0.04600076,  0.31142362,  0.03806789, ..., -0.0216654 ,
        -0.0238827 , -0.08285272],
       [ 0.08944593,  0.12911009,  0.18694721, ..., -0.20369985,
         0.21863466,  0.01886934],
       [ 0.18655866, -0.14833299, -0.13051217, ...,  0.11079313,
         0.23201952,  0.00898361],
       ...,
       [ 0.20444784, -0.06318123, -0.11671099, ..., -0.23931009,
        -0.11131451, -0.13566604],
       [ 0.18144746, -0.01855883,  0.03634938, ..., -0.04590161,
        -0.09434433,  0.26749177],
       [ 0.16611387, -0.03760993,  0.17119139, ..., -0.01924382,
        -0.04079568, -0.22934526]])

In [ ]:
R

array([[ 3.91297841e+02,  3.29667038e+02,  3.13477324e+02, ...,
         3.18936082e+02,  2.83086152e+02,  2.72130303e+02],
       [-1.17332172e-14,  2.59566262e+02,  1.48470217e+02, ...,
         1.14800308e+02,  1.44983507e+02,  1.33848709e+02],
       [ 1.51314382e-15,  1.61835239e-14,  2.71690195e+02, ...,
         1.07093832e+02,  7.97716602e+01,  1.18579082e+02],
       ...,
       [ 7.30031073e-15, -1.79792762e-14, -7.87060987e-15, ...,
         6.63138247e+01,  5.12575544e+01,  9.42888526e+00],
       [-7.88469721e-15,  5.14835836e-15, -2.54735613e-15, ...,
        -8.19821803e-17,  2.29836999e+01,  4.18821436e+01],
       [ 1.42778223e-14,  6.67213470e-15, -9.65102448e-15, ...,
         1.58564094e-15,  1.96560368e-15, -1.83521316e+01]])

In [ ]:
def _givens_rotation_matrix_entries(a, b):
    """Compute matrix entries for Givens rotation."""
    r = hypot(a, b)
    c = a/r
    s = -b/r

    return (c, s)

In [ ]:
def givens_rotation(A):
    """Perform QR decomposition of matrix A using Givens rotation."""
    (num_rows, num_cols) = np.shape(A)

    # Initialize orthogonal matrix Q and upper triangular matrix R.
    Q = np.identity(num_rows)
    R = np.copy(A)

    # Iterate over lower triangular matrix.
    (rows, cols) = np.tril_indices(num_rows, -1, num_cols)
    for (row, col) in zip(rows, cols):

        # Compute Givens rotation matrix and
        # zero-out lower triangular matrix entries.
        if R[row, col] != 0:
            (c, s) = _givens_rotation_matrix_entries(R[col, col], R[row, col])

            G = np.identity(num_rows)
            G[[col, row], [col, row]] = c
            G[row, col] = s
            G[col, row] = -s

            R = np.dot(G, R)
            Q = np.dot(Q, G.T)

    return (Q, R)

In [ ]:
from numpy.lib.function_base import append
import numpy as np
A = np.random.randint(100, size=(50, 50))
A = A.astype('float64')

Q,R=givens_rotation(A)


In [ ]:
Q

array([[ 0.03049728,  0.08760944,  0.09715578, ..., -0.1934125 ,
         0.10198848,  0.23217838],
       [ 0.11495129,  0.15578462,  0.04726188, ..., -0.13974036,
        -0.15089554, -0.20500339],
       [ 0.00938378,  0.24465783, -0.15572759, ..., -0.09584621,
         0.03443719, -0.11513162],
       ...,
       [ 0.09618373, -0.01659398,  0.03439011, ..., -0.08310489,
         0.09658941,  0.01760576],
       [ 0.21817285, -0.0054128 , -0.00668347, ..., -0.08735382,
         0.22368248, -0.1421527 ],
       [ 0.16421612, -0.14221512, -0.08971998, ...,  0.24674013,
         0.14701134, -0.18345009]])

In [ ]:
R

array([[ 4.26267522e+02,  3.40154932e+02,  2.86015222e+02, ...,
         2.80138631e+02,  2.83399494e+02,  3.17145908e+02],
       [-6.59592268e-15,  2.24019245e+02,  1.54417588e+02, ...,
         1.22295131e+02,  1.16709903e+02,  1.55001216e+02],
       [ 7.17809756e-15,  2.41671642e-15,  2.34148460e+02, ...,
         9.40837622e+01,  6.99999011e+01,  6.82495581e+01],
       ...,
       [ 5.39373605e-15, -4.24217818e-15, -3.53833283e-15, ...,
         5.03889860e+01, -1.05545226e+01,  2.82616874e+00],
       [ 1.32311197e-14,  4.51537813e-15, -1.46842704e-15, ...,
        -5.41315076e-16,  7.05718082e+01,  1.29632373e+01],
       [-1.78198827e-15,  9.93688324e-16, -1.37560129e-15, ...,
         1.17211315e-15, -1.64582877e-15, -3.70361716e+01]])

In [ ]:

import numpy as np

def gaussElimination(matrix):
    np.asarray(matrix) 
    matrix = matrix.astype(float)
    print ("the initial matrix:")
    print (matrix)
    if matrix[0,0] == 0.0:
        raise Exception("matrix row 1 column 1 cannot be zero!")
    n,m = matrix.shape
    print ("row:",n,"column:",m)
   
    for i in range(0,n):
        for j in range(i+1,n):
            if matrix[j,i] != 0.0:
                print ("using row ",i,"as pivot and row ",j,"as target")
                multiplier = matrix[j,i]/matrix[i,i]
               
                
                matrix[j,i:m]=matrix[j,i:m] - multiplier*matrix[i,i:m] 
                print (matrix)
                
  
    x = []
    substractor = 0.0
    for i in range(n-1,-1,-1): 
      
        for j in range(0,n-i): 
            
            if j==0:
                substractor = 0
            else:
                substractor = substractor + matrix[i,m-j-1]*x[j-1]
        x.append((matrix[i,m-1]-substractor)/matrix[i,i])
        
    return x


In [ ]:
from numpy.lib.function_base import append
import numpy as np
A = np.random.randint(100, size=(50, 50))
A = A.astype('float64')



In [ ]:
gaussElimination(A)

Görüntülenen çıkış son 5000 satıra kısaltıldı.
 [  0.          0.          0.        ...   6.0326075  57.2514666
  -46.8506082]]
using row  22 as pivot and row  44 as target
[[ 57.         17.         27.        ...  49.          6.
   16.       ]
 [  0.         25.8596491   6.8947368 ...  15.7719298  -6.5789474
   -3.5438596]
 [  0.          0.         59.5705563 ...   8.0481682  96.3792402
   17.7856174]
 ...
 [  0.          0.          0.        ... -38.6848993  72.1788222
  -13.1923045]
 [  0.          0.          0.        ...  38.5357793 154.1385698
  -24.0732268]
 [  0.          0.          0.        ...   6.0326075  57.2514666
  -46.8506082]]
using row  22 as pivot and row  45 as target
[[ 57.         17.         27.        ...  49.          6.
   16.       ]
 [  0.         25.8596491   6.8947368 ...  15.7719298  -6.5789474
   -3.5438596]
 [  0.          0.         59.5705563 ...   8.0481682  96.3792402
   17.7856174]
 ...
 [  0.          0.          0.        ... -38.6848993  

[1.0,
 3.6960289565176483,
 -7.786524414805224,
 14.786221280429663,
 -7.325600351720898,
 -10.964396278819523,
 -19.02664313277498,
 -609.3898596547259,
 620.9466925119453,
 -379.29087137137265,
 1469.7524875360223,
 -3263.1683248703066,
 2329.221945297349,
 5179.201122689754,
 7376.343641102153,
 -8797.130782771193,
 -94220.09525733457,
 79663.45676306156,
 -50577.88962566777,
 1448499.9528864645,
 -1768838.7754841254,
 -243756.51704401846,
 115225.92019301075,
 -1722802.7943617096,
 -1457147.4053006934,
 -2427751.925802839,
 3217833.6019196515,
 -5627722.593534059,
 3617823.7724125767,
 2203027.7219247376,
 -2023287.4096977005,
 12969592.607292391,
 -16856887.90941786,
 4510482.719282533,
 7199659.259545708,
 11937745.872685777,
 -3262074.34640684,
 28834917.139443833,
 -17657942.19496737,
 -155070628.88328493,
 177203036.323759,
 41237828.142896384,
 -121397341.96363659,
 696046124.5108316,
 -683268319.8640786,
 -326538366.1515938,
 791677515.1682544,
 1815023566.070542,
 -52927233

In [ ]:
import numpy as np


def LUDecompose (A):
    # Table that contains our data
    # Table has to be a square array so we need to check first
    rows,columns=np.shape(A)
    L=np.zeros((rows,columns))
    U=np.zeros((rows,columns))
    if rows!=columns:
        return []
    for i in range (columns):
        for j in range(i-1):
            sum=0
            for k in range (j-1):
                sum+=L[i][k]*U[k][j]
            L[i][j]=(A[i][j]-sum)/U[j][j]
        L[i][i]=1
        for j in range(i-1,columns):
            sum1=0
            for k in range(i-1):
                sum1+=L[i][k]*U[k][j]
            U[i][j]=A[i][j]-sum1
    return L,U

In [ ]:
from numpy.lib.function_base import append
import numpy as np
A = np.random.randint(100, size=(50, 50))
A = A.astype('float64')

In [ ]:
LUDecompose(A)

(array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [1.73214286, 0.        , 1.        , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.875     , 2.03571429, 0.80694057, ..., 1.        , 0.        ,
         0.        ],
        [1.75      , 0.78571429, 0.30714001, ..., 0.        , 1.        ,
         0.        ],
        [1.33928571, 2.57142857, 0.70721978, ..., 5.80938999, 0.        ,
         1.        ]]),
 array([[ 5.60000000e+01,  1.70000000e+01,  2.00000000e+00, ...,
          7.40000000e+01,  9.10000000e+01,  3.20000000e+01],
        [ 6.70000000e+01,  2.80000000e+01,  8.60000000e+01, ...,
          2.80000000e+01,  5.00000000e+00,  8.50000000e+01],
        [ 0.00000000e+00,  4.15535714e+01,  8.95357143e+01, ...,
         -1.22178571e+02, -6.96250000e+01,  1.25714286e+01],
        ...,
        [ 0.000000